import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import Navbar from "./components/Navbar/Navbar";

import Modal from "./components/modals/Modal";
import LoginModal from "./components/modals/LoginModal";
import SignupModal from "./components/modals/SignupModal";
import AddPropertyModal from "./components/modals/AddPropertyModal";


const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "DjangoBnb",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {

  const closer = () => { console.log(); }

  return (
    <html lang="en">
      <body className={inter.className}>
        <Navbar></Navbar>

        <div className="pt-32">
          {children}
        </div>

        <LoginModal></LoginModal>

        <SignupModal></SignupModal>

        <AddPropertyModal></AddPropertyModal>

      </body>
    </html>
  );
}
